<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BusinessTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('business')->delete();
        
        \DB::table('business')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'HOTEL ALMA',
                'person_id' => 1,
                'job_types_id' => 7,
                'nit' => '1905949-16',
                'description' => 'Hospedaje, Suit,Matrimoniales, Dobles y sincilla.',
                'address' => 'C/ Cipriano Barace al lado de Entel',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 79208809,
                'city_id' => 1,
                'status' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'COVER',
                'person_id' => 2,
                'job_types_id' => 8,
                'nit' => '4717827',
                'description' => 'Venta de accesorios para celulares,',
                'address' => 'C/ Cipriano Barace al lado de FEGABENI',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 78748414,
                'city_id' => 1,
                'status' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'STORE MANIA',
                'person_id' => 3,
                'job_types_id' => 8,
                'nit' => '12880823',
                'description' => 'Venta de accesorios para celulares,',
                'address' => 'C/Cipriano Barace al frente de Entel',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 76868730,
                'city_id' => 1,
                'status' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'GERLD SHOPP',
                'person_id' => 4,
                'job_types_id' => 8,
                'nit' => '13624184',
                'description' => 'Venta de accesorios para celulares,',
                'address' => 'C/Cipriano Barace al frente de Entel',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 67216263,
                'city_id' => 1,
                'status' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'MEGA CENTER',
                'person_id' => 5,
                'job_types_id' => 9,
                'nit' => '12187879',
                'description' => 'Venta de celulares y accesorios para celulares,',
                'address' => 'C/Cipriano Barace al frente de Entel',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 7282992,
                'city_id' => 1,
                'status' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'CLUB SOCIAL',
                'person_id' => 6,
                'job_types_id' => 10,
                'nit' => '4192149',
                'description' => 'Salon de eventos y venta de comida.',
                'address' => 'Calle Manuel Limpias al frente de la Plaza Central',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 70265420,
                'city_id' => 1,
                'status' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'LIBRER?A BAZAR JUVENTUD',
                'person_id' => 7,
                'job_types_id' => 11,
                'nit' => '1736426',
                'description' => 'Venta de Material Escolar y de escritorio.',
                'address' => 'C/Nicolas Suarez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 78285198,
                'city_id' => 1,
                'status' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'LIBRER?A SOLO CELL',
                'person_id' => 8,
                'job_types_id' => 11,
                'nit' => '5263302',
                'description' => 'Venta de materias escolar, escrito y sellos.',
                'address' => 'C/Nicolas Suarez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 70263715,
                'city_id' => 1,
                'status' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'HAPPY FIS',
                'person_id' => 9,
                'job_types_id' => 12,
                'nit' => '1920690',
                'description' => 'Venta de Calzados para niños y adultos.',
                'address' => 'Calle Antonio Vaca Diez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 69386872,
                'city_id' => 1,
                'status' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'PILCHAS',
                'person_id' => 10,
                'job_types_id' => 13,
                'nit' => '1907584',
                'description' => 'Venta de ropa y accesorios para mujeres.',
                'address' => 'Calle Antonio Vaca Diez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 72838223,
                'city_id' => 1,
                'status' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'BLAW & WMITE',
                'person_id' => 11,
                'job_types_id' => 13,
                'nit' => '1709952',
                'description' => 'Venta de ropa y accesorios para mujeres.',
                'address' => 'Calle Antonio Vaca Diez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 68967425,
                'city_id' => 1,
                'status' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'FRANAFRANCH',
                'person_id' => 12,
                'job_types_id' => 13,
                'nit' => '401145',
                'description' => 'Venta de Ropa y Calzados para dama.',
                'address' => 'Calle Antonio Vaca Diez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 69177040,
                'city_id' => 1,
                'status' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'NEW PRINT',
                'person_id' => 13,
                'job_types_id' => 14,
                'nit' => '5616133',
                'description' => 'Venta de sellos ',
                'address' => 'C/ 18 de noviembre',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 60360117,
                'city_id' => 1,
                'status' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'IMPRENTA GRAFICAR',
                'person_id' => 14,
                'job_types_id' => 14,
                'nit' => '72830627',
                'description' => 'Venta y diseño de ropa deportiva',
                'address' => 'C/ 18 de noviembre',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 72830627,
                'city_id' => 1,
                'status' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'TIENDA DE ROPA A TU MEDIDA',
                'person_id' => 15,
                'job_types_id' => 15,
                'nit' => '1760694',
                'description' => 'Venta de ropa, calzados y accesorios para mujeres',
                'address' => 'C/ 18 de noviembre',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 71124460,
                'city_id' => 1,
                'status' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'LICORERIA OLDPARR',
                'person_id' => 16,
                'job_types_id' => 16,
                'nit' => '4175412',
                'description' => 'Venta de Bebidas y botanas',
                'address' => 'Av. 6 de agosto',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 72819285,
                'city_id' => 1,
                'status' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'PARABERO SPORT',
                'person_id' => 17,
                'job_types_id' => 15,
                'nit' => '5622917',
                'description' => 'Venta y diseño de ropa deportiva',
                'address' => 'Av. 6 de agosto',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 70274007,
                'city_id' => 1,
                'status' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'MOTOCICLETAS TVS',
                'person_id' => 18,
                'job_types_id' => 17,
                'nit' => '1029831027',
                'description' => 'Venta de motocletas y servicio mecanico.',
                'address' => 'C/ Santa Cruz Sur',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 74164333,
                'city_id' => 1,
                'status' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'BOUTIQUE YENIAR',
                'person_id' => 19,
                'job_types_id' => 13,
                'nit' => '1052155',
                'description' => 'Venta de ropa para Hombre.',
                'address' => 'C/ Antono Vaca Diez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 4622946,
                'city_id' => 1,
                'status' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'TIENDA DE MODA BONITA',
                'person_id' => 20,
                'job_types_id' => 13,
                'nit' => '12377748',
                'description' => 'Venta de ropa y accesorios para mujeres',
                'address' => 'C/ Antono Vaca Diez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 69375045,
                'city_id' => 1,
                'status' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'TIENDA ROSA Y AZUL',
                'person_id' => 21,
                'job_types_id' => 13,
                'nit' => '10854446',
                'description' => 'Venta de ropa y accesorios para niñas y niños.',
                'address' => 'C/ Antono Vaca Diez',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 72826420,
                'city_id' => 1,
                'status' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'CALZADOS MAYEL',
                'person_id' => 22,
                'job_types_id' => 12,
                'nit' => '12188793',
                'description' => 'Venta de Calzados para damas.',
                'address' => 'C/ 18 de noviembre',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 78298603,
                'city_id' => 1,
                'status' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'ADONIS',
                'person_id' => 23,
                'job_types_id' => 18,
                'nit' => '5613860',
                'description' => 'Salon, estetica y peluqueria unisex.',
                'address' => 'C/ 18 de noviembre',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 72813660,
                'city_id' => 1,
                'status' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'TRINI HOME',
                'person_id' => 24,
                'job_types_id' => 19,
                'nit' => '3104473',
                'description' => 'Ventas y servicios tecnicos de Computadoras e impresoras mas accesorios',
                'address' => 'C/ 18 de noviembre',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'phone' => 71285403,
                'city_id' => 1,
                'status' => 1,
            ),
        ));
        
        
    }
}