<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PeopleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        // \DB::table('people')->delete();
        
        \DB::table('people')->insert(array (
            0 => 
            array (
                'id' => 63,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Mabel ',
                'last_name' => 'Becerra Aguilera',
                'dni' => '1905949-16',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '79208809',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 64,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Carmen',
                'last_name' => 'Rosa Rocha',
                'dni' => '4717827',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '78748414',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 65,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Alison',
                'last_name' => 'Escalante Rocha',
                'dni' => '12880823',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '76868730',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 66,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Rebeca',
                'last_name' => 'Taquichiri Janco',
                'dni' => '13624184',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '67216263',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 67,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Gary',
                'last_name' => 'Cuaere',
                'dni' => '12187879',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '7282992',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 68,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Lourdes Yely',
                'last_name' => 'Ribera Cuellar',
                'dni' => '4192149',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '70265420',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 69,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Geovani Oscar',
                'last_name' => 'Ferrufino Vargas',
                'dni' => '1736426',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '78285198',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 70,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Silvana',
                'last_name' => 'Flores Perez',
                'dni' => '5263302',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '70263715',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 71,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Maria Luisa',
                'last_name' => 'Salina Zabala',
                'dni' => '1920690',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '69386872',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 72,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Claudia',
                'last_name' => 'Mercado Vaca',
                'dni' => '1907584',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '72838223',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 73,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Adelia',
                'last_name' => 'Montenegro Rodriguez',
                'dni' => '1709952',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '68967425',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 74,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Valeria',
                'last_name' => 'Antelo',
                'dni' => '401145',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '69177040',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 75,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Juan Carlos',
                'last_name' => 'Ramirez Rodriguez',
                'dni' => '5616133',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '60360117',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 76,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Miguel',
                'last_name' => 'Alvarez Muiba',
                'dni' => '72830627',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '72830627',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 77,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Visnia Tereza',
                'last_name' => 'Suarez A?ez',
                'dni' => '1760694',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '71124460',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 78,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Aldo',
                'last_name' => 'Bravo Sotto',
                'dni' => '4175412',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '72819285',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 79,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Carlos JR',
                'last_name' => 'Montero Ribera',
                'dni' => '5622917',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '70274007',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 80,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Carola',
                'last_name' => 'Melgar',
                'dni' => '1029831027',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '74164333',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 81,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Yenniar',
                'last_name' => 'Rivero',
                'dni' => '1052155',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '46-22946',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 82,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Isela',
                'last_name' => 'Guagama Becerra',
                'dni' => '12377748',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '69375045',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 83,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Lizeth',
                'last_name' => 'Peres Ribera',
                'dni' => '10854446',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '72826420',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 84,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Mayel',
                'last_name' => 'Rivera Yelma',
                'dni' => '12188793',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '78298603',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 85,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Algel Leonardo',
                'last_name' => 'Lopez Alvarez',
                'dni' => '5613860',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '72813660',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 86,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'Elizabeth',
                'last_name' => 'Ledesma Vila',
                'dni' => '3104473',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '71285403',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => NULL,
                'long_description' => NULL,
                'type' => 2,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 87,
                'city_id' => 1,
                'job_id' => 34,
                'first_name' => 'CARLOS MANUEL',
                'last_name' => 'MOYE MOYE',
                'dni' => '14612689',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '14612689',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'MESERO EN RESTAURANTE',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 88,
                'city_id' => 1,
                'job_id' => 35,
                'first_name' => 'MATIAS',
                'last_name' => 'GUASEBE GUASOMA',
                'dni' => '14209227',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '14209227',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'REALIZO EL TRABAJO DE LIMPIEZA EN PATIO DE COMIDA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 89,
                'city_id' => 1,
                'job_id' => 34,
                'first_name' => 'MARIA DEL ROSARIO',
                'last_name' => 'SOTTO MOSQUEIRA',
                'dni' => '16961693',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '68974038',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'MESERA EN RESTAURANTE ATENCION AL CLIENTE Y LIMPIEZA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 90,
                'city_id' => 1,
                'job_id' => 35,
                'first_name' => 'JOSELIN',
                'last_name' => 'MENACHO MOSQUEIRA',
                'dni' => '15031558',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '68974038',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'REALIZO EL TRABAJO DE LIMPIEZA EN PATIO DE COMIDA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 91,
                'city_id' => 1,
                'job_id' => 34,
                'first_name' => 'MARCO ANTONIO',
                'last_name' => 'CASTEDO ROMERO',
                'dni' => '15953351',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '72921366',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'MESERO EN RESTAURANTE',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 92,
                'city_id' => 1,
                'job_id' => 34,
                'first_name' => 'LUCIANA',
                'last_name' => 'PAZ RIVERO',
                'dni' => '12880940',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '67533261',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'LIMPIEZA EN LAGUNA JARDIN',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 93,
                'city_id' => 1,
                'job_id' => 36,
                'first_name' => 'LUIS GUSTAVO',
                'last_name' => 'ARCE CALLAU',
                'dni' => '13008601',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '69568808',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'AYUDANTE DE COCINA EN CHURRASQUERIA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 94,
                'city_id' => 1,
                'job_id' => 36,
                'first_name' => 'DANIEL',
                'last_name' => 'NOZA CUEVAS',
                'dni' => '14437978-1',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '69383028',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'AYUDANTE DE COCINA EN CHURRASQUERIA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 95,
                'city_id' => 1,
                'job_id' => 36,
                'first_name' => 'PAUL JUNIOR',
                'last_name' => 'SOTTO MOSQUEIRA',
                'dni' => '16961797',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '68974038',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'GASTRONOMIA AYUDANTE DE COCINA EN RESTAURANTE FLAMINGO\'S',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 96,
                'city_id' => 1,
                'job_id' => NULL,
                'first_name' => 'LUIS ROQUE',
                'last_name' => 'DIEZ VARGAS',
                'dni' => '10856400',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '10856400',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'REPONEDOR EN SUPERMERCADO',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 97,
                'city_id' => 1,
                'job_id' => 36,
                'first_name' => 'ROGER',
                'last_name' => 'ORTIZ MEDINA',
                'dni' => '14209228',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '73900836',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'ELABORACION Y PREPARACION DE PIZZA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 98,
                'city_id' => 1,
                'job_id' => 36,
                'first_name' => 'EDUARDO',
                'last_name' => 'SANCHEZ TUBE',
                'dni' => '15821339',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '68973502',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'ELABORACION Y PREPARACION DE POLLO A LA BROASTER',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 99,
                'city_id' => 1,
                'job_id' => 36,
                'first_name' => 'EDUARDO',
                'last_name' => 'MACABAPI MALELE',
                'dni' => '13991960',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '68958945',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'ELABORACION Y PREPARADO DE COMIDA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 100,
                'city_id' => 1,
                'job_id' => 36,
                'first_name' => 'NHAGTLIG',
                'last_name' => 'JUSTINIANO NOCO',
                'dni' => '15347464',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '63372745',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'PREPARACION DE PASTAS Y COMIDA RAPIDA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 101,
                'city_id' => 1,
                'job_id' => 35,
                'first_name' => 'GERSON ',
                'last_name' => 'JUSTINIANO NOCO',
                'dni' => '15347499',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '63372745',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'LIMPIEZA EN RESTAURANTE DE COMIDA RAPIDA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 102,
                'city_id' => 1,
                'job_id' => 36,
                'first_name' => 'FRANCISCO',
                'last_name' => 'PAZ NOZA',
                'dni' => '14677511',
                'gender' => 'masculino',
                'birthday' => NULL,
                'phone' => '69369086',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'AYUDANTE DE COCINA EN CHURRASQUERIA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 103,
                'city_id' => 1,
                'job_id' => 34,
                'first_name' => 'ANDREA',
                'last_name' => 'CUELLAR ROCA',
                'dni' => '14739095',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '74582984',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'MESERA EN RESTAURANTE ATENCION AL CLIENTE  EN BALNEARIO',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 104,
                'city_id' => 1,
                'job_id' => 35,
                'first_name' => 'SARELA',
                'last_name' => 'CESPEDES SUAREZ',
                'dni' => '108300205',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '67275870',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'LIMPIEZA EN UN BALNEARIO',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 105,
                'city_id' => 1,
                'job_id' => 34,
                'first_name' => 'MILAGROS',
                'last_name' => 'GUASINAVE GUAJI',
                'dni' => '13008242',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '13008242',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'MESERA EN RESTAURANTE ATENCION AL CLIENTE  EN BALNEARIO',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 106,
                'city_id' => 1,
                'job_id' => 34,
                'first_name' => 'PURA BEATRIZ',
                'last_name' => 'MENACHO DURAN',
                'dni' => '13831476',
                'gender' => 'femenino',
                'birthday' => NULL,
                'phone' => '76863385',
                'address' => NULL,
                'photo' => NULL,
                'video' => NULL,
                'short_description' => 'MESERA EN CHURRASQUERIA',
                'long_description' => NULL,
                'type' => 1,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}